version: '3.3'
services:
  go:
    build: .
    restart: always
    environment:
      JWT_EXPIRE_DAYS: 14
      JWT_ISSUER: DefaultIssuer
      JWT_SECRET: DefaultJwtSecret

      MYSQL_DB: DefaultDb
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: DefaultPassword
      MYSQL_PORT: 3306
      MYSQL_USER: root

      PAGE_SIZE: 30

      REDIS_HOST: redis
      REDIS_PASSWORD: DefaultPassword
      REDIS_PORT: 6379
      REDIS_DB: 0

      CELERY_TASK: tasks

      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_TOKEN: DefaultPassword
      INFLUXDB_ORG: DefaultOrg
      INFLUXDB_BUCKET: DefaultBucket

      CHROMA_HOST: chroma-client
      CHROMA_PORT: 8888
      CHROMA_QUERY_NUM: 3

    depends_on:
      - redis
      - mysql
      - influxdb
    volumes:
      - logs_directory:/logs
      - ./../private_key:/app/private_key

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass DefaultPassword
    volumes:
      - test_redis_data:/data

  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - test_my_sql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DefaultPassword
      - MYSQL_USER=DefaultUser
      - MYSQL_PASSWORD=DefaultPassword
      - MYSQL_DATABASE=DefaultDb

  chroma:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - test_chroma-storage:/chroma

  chroma-client:
    image: chroma-client-image
    restart: always
    environment:
      - CHROMADB_HOST=chroma
      - CHROMADB_PORT=8000
      - CHROMADB_COLLECTION=DefaultCollection

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=DefaultUser
      - GF_SECURITY_ADMIN_PASSWORD=DefaultPassword
    volumes:
      - grafana-storage:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=DefaultUser
      - DOCKER_INFLUXDB_INIT_PASSWORD=DefaultPassword
      - DOCKER_INFLUXDB_INIT_ORG=DefaultOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=DefaultBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=DefaultPassword
    volumes:
      - influxdb-storage:/var/lib/influxdb

  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  nginx:
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./../tcweeei.study-savvy.com:/tcweeei.study-savvy.com
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node_exporter:
    restart: always
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"

volumes:
  grafana-storage:
  influxdb-storage:
  logs_directory:
  test_my_sql_data:
    external: true
  test_redis_data:
    external: true
  test_chroma-storage:
    external: true