### Edit Password
PUT {{BASE_URL}}/api/v1/user/edit_password
Authorization: Bearer {{EXAMPLE_JWT}}
Content-Type: application/json

{
  "current_password": "{{EXAMPLE_PASSWORD}}",
  "edit_password": "{{EXAMPLE_EDIT_PASSWORD}}"
}

### Reformat Password
PUT {{BASE_URL}}/api/v1/user/edit_password
Authorization: Bearer {{EXAMPLE_JWT}}
Content-Type: application/json

{
  "current_password": "{{EXAMPLE_EDIT_PASSWORD}}",
  "edit_password": "{{EXAMPLE_PASSWORD}}"
}
